language: python

python:
  - "3.6"

install:
  - pip install -r requirements-dev.txt
  - python setup.py install

script:
  - python setup.py test
  - find . -type f -name "*.py" | xargs flake8

after_success:
  - python setup.py sdist bdist_wheel --universal
